apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    annotations:
      meta.helm.sh/release-name: prometheus
      meta.helm.sh/release-namespace: monitor
    creationTimestamp: "2021-04-04T15:00:24Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/managed-by: Helm
      chart: kube-prometheus-stack-12.10.6
      heritage: Helm
      release: prometheus
      manager: Go-http-client
      operation: Update
      time: "2021-04-04T15:00:24Z"
    name: prometheus-kube-prometheus-prometheus
    namespace: monitor
    resourceVersion: "13433"
    uid: 128c8a5f-af47-47e8-9a94-6d60129023dd
  spec:
    alerting:
      alertmanagers:
      - apiVersion: v2
        name: prometheus-kube-prometheus-alertmanager
        namespace: monitor
        pathPrefix: /
        port: web
    enableAdminAPI: false
    externalUrl: http://prometheus-kube-prometheus-prometheus.monitor:9090
    image: quay.io/prometheus/prometheus:v2.22.1
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector:
      matchLabels:
        release: prometheus
    portName: web
    probeNamespaceSelector: {}
    probeSelector:
      matchLabels:
        release: prometheus
    replicas: 1
    retention: 10d
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        app: kube-prometheus-stack
        release: prometheus
    secrets:
    - etcd-client-cert
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    additionalScrapeConfigs:
      name: prometheus-additional-configs
      key: prometheus-additional.yaml 
    serviceAccountName: prometheus-kube-prometheus-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
    version: v2.22.1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
